version: '3.4'

services:
  pdfmerge:
    restart: always
    container_name: pdfmerge
    image: joschuster/pdfmerge
    volumes:
      - "/volume1/public/scan/duplexinbox:/input"
      - "/volume1/public/scan/inbox:/output"
      - "/etc/localtime:/etc/localtime:ro"
    environment: 
      - ODD_PAGES_PATTERN=front
      - EVEN_PAGES_PATTERN=back
    user: "<user-id>:<group-id>"
    entrypoint: python3
    command: watcher.py
